//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDetails", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class CustomerDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BRANCH_NAMEField;
        
        private string CUSTOMER_NAMEField;
        
        private string DTM_APPROVEDField;
        
        private string DTM_END_SENDField;
        
        private string DTM_START_SENDField;
        
        private string ESTAR_APPIDField;
        
        private string FIELD_NOTEField;
        
        private string PRODUCT_TYPEField;
        
        private string SURVEYOR_NAMEField;
        
        private string TASK_IDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BRANCH_NAME
        {
            get
            {
                return this.BRANCH_NAMEField;
            }
            set
            {
                this.BRANCH_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUSTOMER_NAME
        {
            get
            {
                return this.CUSTOMER_NAMEField;
            }
            set
            {
                this.CUSTOMER_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DTM_APPROVED
        {
            get
            {
                return this.DTM_APPROVEDField;
            }
            set
            {
                this.DTM_APPROVEDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DTM_END_SEND
        {
            get
            {
                return this.DTM_END_SENDField;
            }
            set
            {
                this.DTM_END_SENDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DTM_START_SEND
        {
            get
            {
                return this.DTM_START_SENDField;
            }
            set
            {
                this.DTM_START_SENDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTAR_APPID
        {
            get
            {
                return this.ESTAR_APPIDField;
            }
            set
            {
                this.ESTAR_APPIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIELD_NOTE
        {
            get
            {
                return this.FIELD_NOTEField;
            }
            set
            {
                this.FIELD_NOTEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODUCT_TYPE
        {
            get
            {
                return this.PRODUCT_TYPEField;
            }
            set
            {
                this.PRODUCT_TYPEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SURVEYOR_NAME
        {
            get
            {
                return this.SURVEYOR_NAMEField;
            }
            set
            {
                this.SURVEYOR_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TASK_ID
        {
            get
            {
                return this.TASK_IDField;
            }
            set
            {
                this.TASK_IDField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerDetails", ReplyAction="http://tempuri.org/IService1/GetCustomerDetailsResponse")]
    WcfService1.CustomerDetails[] GetCustomerDetails(string CustomerName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerDetails", ReplyAction="http://tempuri.org/IService1/GetCustomerDetailsResponse")]
    System.Threading.Tasks.Task<WcfService1.CustomerDetails[]> GetCustomerDetailsAsync(string CustomerName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomerDetails", ReplyAction="http://tempuri.org/IService1/InsertCustomerDetailsResponse")]
    string InsertCustomerDetails(WcfService1.CustomerDetails customerInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomerDetails", ReplyAction="http://tempuri.org/IService1/InsertCustomerDetailsResponse")]
    System.Threading.Tasks.Task<string> InsertCustomerDetailsAsync(WcfService1.CustomerDetails customerInfo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WcfService1.CustomerDetails[] GetCustomerDetails(string CustomerName)
    {
        return base.Channel.GetCustomerDetails(CustomerName);
    }
    
    public System.Threading.Tasks.Task<WcfService1.CustomerDetails[]> GetCustomerDetailsAsync(string CustomerName)
    {
        return base.Channel.GetCustomerDetailsAsync(CustomerName);
    }
    
    public string InsertCustomerDetails(WcfService1.CustomerDetails customerInfo)
    {
        return base.Channel.InsertCustomerDetails(customerInfo);
    }
    
    public System.Threading.Tasks.Task<string> InsertCustomerDetailsAsync(WcfService1.CustomerDetails customerInfo)
    {
        return base.Channel.InsertCustomerDetailsAsync(customerInfo);
    }
}
