//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerDetails", ReplyAction="http://tempuri.org/IService1/GetCustomerDetailsResponse")]
        WcfService1.CustomerDetails[] GetCustomerDetails(string CustomerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerDetails", ReplyAction="http://tempuri.org/IService1/GetCustomerDetailsResponse")]
        System.Threading.Tasks.Task<WcfService1.CustomerDetails[]> GetCustomerDetailsAsync(string CustomerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomerDetails", ReplyAction="http://tempuri.org/IService1/InsertCustomerDetailsResponse")]
        string InsertCustomerDetails(WcfService1.CustomerDetails customerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomerDetails", ReplyAction="http://tempuri.org/IService1/InsertCustomerDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertCustomerDetailsAsync(WcfService1.CustomerDetails customerInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IService1>, WebApplication1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfService1.CustomerDetails[] GetCustomerDetails(string CustomerName) {
            return base.Channel.GetCustomerDetails(CustomerName);
        }
        
        public System.Threading.Tasks.Task<WcfService1.CustomerDetails[]> GetCustomerDetailsAsync(string CustomerName) {
            return base.Channel.GetCustomerDetailsAsync(CustomerName);
        }
        
        public string InsertCustomerDetails(WcfService1.CustomerDetails customerInfo) {
            return base.Channel.InsertCustomerDetails(customerInfo);
        }
        
        public System.Threading.Tasks.Task<string> InsertCustomerDetailsAsync(WcfService1.CustomerDetails customerInfo) {
            return base.Channel.InsertCustomerDetailsAsync(customerInfo);
        }
    }
}
